<?php

//Informações adicionais

echo "<p><center><br><br><font face=arial><font color=cc0000 size=5><b>FIM DO TESTE</b></font><br><br><br>
Muito bem, <font face=arial><font color=#8B4513 size=3>$nome!</font> por responder o teste. Seu próximo passo é agendar uma entrevista, para que possamos dar-lhe o resultado pessoalmente,<b>sem nenhum custo.</b>
<p>Obs: Este teste tem validade de no máximo 15 dias.<br>
<p>Um de <b>nossos consultores treinados entrará em contato</b> através dos dados fornecidos para passar-lhe mais informações. <br>Você também pode entrar em contato conosco pelo whatsapp:<font face=arial><font color=#32CD32 size=3><b> <a href= 'https://api.whatsapp.com/send?phone=5581996382894&text=Digite%20uma%20mensagem' target='_blank'>(81) 99638-2894</a></b></font><p>";

?>