<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="pt-BR">
<head profile="http://gmpg.org/xfn/11">
<meta charset="UTF-8">
<meta name="keywords" content="new, era, dianetics, dianetic, auditing, what is scientology, hubbard, technology, books, information, ron, book, evolution, watch, movies, videos, video, free, movie, downloads, online, internet, clear, preclear, state, reactive, mind, nova era, dianética, auditoria, Dianetic, o que é cientologia, hubbard, tecnologia, livros, informação, ron, o livro, a evolução, relógio, filmes, vídeos, video, filme, free, downloads, online, internet, claro, preclear, Estado, reativa, mente">
<meta name="description" content="Site Brasileiro de Dianética. Assista depoimentos em filmes de vídeo, compre livros por L Ron Hubbard sobre mente reativa, as fontes de stress, insegurança e infelicidade. A nova era da ciência da mente humana para desbloquear o seu potencial pleno.">
<title>Análise de Potencial Pessoal - Instruções</title>
<link rel="stylesheet" type="text/css" media="all" href="style.css"/>
</head>
<body>

<TABLE cellSpacing=0 cellPadding=0 width=530 border=0 align=center>
<TBODY>

<TR bgcolor="black"><TD vAlign=center height=30 align=middle >
<img align=right src='ocatm.gif' />
</td><tr>
</TBODY></TABLE>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19814769-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>